version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/lib"
    schedule:
      interval: weekly
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: weekly
  - package-ecosystem: "cargo"
    directory: "/cli"
    schedule:
      interval: weekly
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
