accepted = [
	"Unlicense",        # https://spdx.org/licenses/Unlicense
	"CC0-1.0",          # https://spdx.org/licenses/CC0-1.0
	"MIT",              # https://spdx.org/licenses/MIT
	"BSD-3-Clause",     # https://spdx.org/licenses/BSD-3-Clause
	"Zlib",             # https://spdx.org/licenses/Zlib
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
	"Unicode-3.0",      # https://spdx.org/licenses/Unicode-3.0
	"MPL-2.0",          # https://spdx.org/licenses/MPL-2.0
]

targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
]

no-clearly-defined = true
