accepted = [
	"Unlicense",        # https://spdx.org/licenses/Unlicense
	"CC0-1.0",          # https://spdx.org/licenses/CC0-1.0
	"MIT",              # https://spdx.org/licenses/MIT
	"ISC",              # https://spdx.org/licenses/ISC
	"BSD-3-Clause",     # https://spdx.org/licenses/BSD-3-Clause
	"Zlib",             # https://spdx.org/licenses/Zlib
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
	"Unicode-3.0",      # https://spdx.org/licenses/Unicode-3.0
	"MPL-2.0",          # https://spdx.org/licenses/MPL-2.0
]

workarounds = ["ring"]

targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
	"aarch64-linux-android",
	"arm-linux-androideabi",
	"armv7-linux-androideabi",
	"i686-linux-android",
	"thumbv7neon-linux-androideabi",
	"x86_64-linux-android",
	"riscv64-linux-android",
]

no-clearly-defined = true

[ring]
accepted = ["OpenSSL"]

[webpki.clarify]
license = "ISC AND BSD-3-Clause"

[[webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"

[[webpki.clarify.files]]
path = "third-party/chromium/LICENSE"
license = "BSD-3-Clause"
checksum = "845022e0c1db1abb41a6ba4cd3c4b674ec290f3359d9d3c78ae558d4c0ed9308"
