[graph]
all-features = true
targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
	"aarch64-linux-android",
	"arm-linux-androideabi",
	"armv7-linux-androideabi",
	"i686-linux-android",
	"thumbv7neon-linux-androideabi",
	"x86_64-linux-android",
]

[advisories]
version = 2
ignore = []

[licenses]
version = 2
confidence-threshold = 0.9
unused-allowed-license = "allow"
allow = [
	"Unlicense",        # https://spdx.org/licenses/Unlicense
	"CC0-1.0",          # https://spdx.org/licenses/CC0-1.0
	"MIT",              # https://spdx.org/licenses/MIT
	"ISC",              # https://spdx.org/licenses/ISC
	"BSD-3-Clause",     # https://spdx.org/licenses/BSD-3-Clause
	"Zlib",             # https://spdx.org/licenses/Zlib
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
	"Unicode-3.0",      # https://spdx.org/licenses/Unicode-3.0
	"MPL-2.0",          # https://spdx.org/licenses/MPL-2.0
]
exceptions = []

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "rustls-webpki"
version = "*"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[licenses.private]
ignore = true

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
