[package]
name = "pinger-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", default-features = false, features = [
	"http1",
	"http2",
	"tokio",
	"tower-log",
	"tracing",
	"macros",
	"ws",
] }
base64 = "0.22.1"
pinger = { version = "*", path = "../lib" }
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
	"env-filter",
	"tracing-log",
] }

[dev-dependencies]
regex = "1.10.4"
