[package]
name = "pinger-cli"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
colored = "2.1.0"
base64 = "0.22.1"
derive_more = { version = "0.99.18", default-features = false, features = [
	"display",
] }
futures-util = "0.3.31"
pinger = { version = "*", path = "../lib" }
rustls = { version = "0.23.14", default-features = false, features = [
	"ring",
	"log",
	"logging",
	"std",
	"tls12",
] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = [
	"rustls-tls-native-roots",
] }
inquire = "0.7.5"
