name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["backend", "cli", "lib"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --manifest-path ${{ matrix.dir }}/Cargo.toml

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["backend", "cli", "lib"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --manifest-path ${{ matrix.dir }}/Cargo.toml

  fmt:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["backend", "cli", "lib"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --manifest-path ${{ matrix.dir }}/Cargo.toml --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["backend", "cli", "lib"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy --all --manifest-path ${{ matrix.dir }}/Cargo.toml -- -D warnings
